### ISSUE TITLE
Add systemctl daemon-reload

### ISSUE THREAD

**Issue by ghost** [bertvv/cheat-sheets#8]
I use `systemctl daemon-reload` all the time after editing or moving a systemd unit file. It reloads the systemd manager configuration so that next time the systemd uses the unit file it will use the latest one with the changes.  I guess it is sort of the sysV equivalent of `chkconfig --add some_sysv_init_file`

Thanks for the cheat-sheet.

**Comment by bertvv** [comment]
Thanks for the suggestion. However, as I said in the README, a cheat sheet is personal. I haven't needed `daemon-reload`, so it doesn't fit in _my_ cheat sheet. However, feel free to fork the project and adapt it to your own needs!
