### ISSUE TITLE
Bash notes 

### ISSUE THREAD

**Issue by skull-squadron** [bertvv/cheat-sheets#9]
1.  `trap` must save and restore exit code, or may always become the status of the last statemetn in `finish`.

        finish() {
          RESULT=$?
          # your cleanup code here
          exit $RESULT
        }

        trap finish EXIT ERR

        trap - EXIT ERR # if trap isn’t needed anymore

2. Don’t bother typing out `function`, just use `()` after the function name.
3. "" around everything that can contain whitespace or a separator, if it must fit in a variable or one argument.
4. Almost always `set -e` at top of scripts because failed commands should usually fail scripts.
5. `set -x` at the top of scripts or use `bashdb` to debug scripts.
6. Some loops happen in subprocesses, so don’t be surprised when setting vars does nothing after them. Use stdout and greping to communicate status.
7. Don’t use `cd foo ... cd ..`, use `(cd foo ...)`
8. Print errors on stderr, not stdout
9. Name heredoc tags with what they’re part of, like

        <<HELP
        usage $0 [args...] {file}

        HELP
10. Single-quote heredocs leading tag to prevent interpolation of text between them.
11. Use `nohup foo | cat &` if `foo` must be started from a terminal and run in the background.
12. Bash can be used for tcp/udp servers and connections, you don’t need `curl` or `wget`. Give examples.
13. Make `rbash` the unchangeable default on ssh jumpboxes.
14. Use any command stdin, stdout or both as a file passed to any other command. `cat <(cat /etc/hosts); cat <>(cat)`
15. Use `echo whatever | sudo tee /path/to/file >/dev/null` to write any file as root.
16. Never `rm -rf "${dir}"` could be crossing-the-streams bad. Use `rm -rf -- "${var}"` instead. Typing out full args is absolutely pointless busywork.

**Comment by bertvv** [comment]
Thank you so much for taking the time to formulate such detailed and useful tips. I'll be sure to incorporate them in my Bash cheat sheet.

**Comment by bertvv** [comment]
A few responses to your remarks:

* 12 - Using Bash for TCP/UDP connections may be neat, but it does not improve readability of the script, on the contrary. I wouldn't use this in a script. `curl` and `wget` are well understood.
* 14 - I don't understand these examples?
* 16 - I most emphatically disagree with

    > Typing out full args is absolutely pointless busywork.

    Maybe `rm -rf` is a bad example because everyone knows what these options mean. However, I personally do not remember the meaning of all short options of all commands I use in a script. By using the long options, I immediately know what's happening without having to look them up in the man page.

In my coding style, I do *not* try to achieve Bash (or Bourne shell) purism. My goal is to write "clean code", i.e. readable code that's still understandable a year (or longer) after it's been written, and that pretty much does what you would expect. Bash's sometimes arcane syntax is sometimes a barrier in that regard.

But of course, this is only an opinion! I appreciate the comments anyway and it's always interesting to see other opinions. I certainly learned a thing or two, so thank you!
